<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms & Conditions</title>
    <?php require_once 'partials/head.php' ?>
</head>

<body>
    <?php require_once 'partials/navbar.php' ?>
    <style>
        h1 {
            font-size: 2rem;
            text-align: center;
            font-weight: 800;
        }

        h2,
        h3 {

            text-align: center;
        }

        h2 {
            font-size: 20px;
            margin-top: 20px;
        }

        ol {
            list-style-type: lower-alpha;
        }

        li {
            margin-bottom: 10px;
        }

        p,
        body li,
        a,
        {
        padding: 10px;
        color: black;
        }
    </style>
    <div class="container">

        <h1>BIOALEXIS TRADING INDIA PRIVATE LIMITED</h1>
        <h2>Independent Business Associate Agreement</h2>
        <h3>(RULES, TERMS AND CONDITIONS)</h3>

        <h2>Terms and Conditions</h2>
        <br>
        <ol>
            <li>
                The BIOALEXIS TRADING INDIA PRIVATE LIMITED (herein after referred as the "COMPANY") reserves all rights
                whether
                to
                accept the application of applicant for An Independent Business Associate (herein after referred as the
                "Direct
                Seller")
                or reject whatsoever and it is final and binding on the applicant. On Selection as DIRECT SELLER an
                unique
                Identification No. will be issued. He / She henceforth are eligible for certain incentives like
                discounts/
                Commission
                and rewards as detailed in the business plan of the company.
            </li>

            <li>
                Company and Direct Seller enter into this agreement both the parties have rights and obligation that are
                coextensive
                with the rights and obligations of the parties under the Indian Contract Act 1872.
            </li>

            <li>
                The applicant must be 18 years or above of age and shall be competent to enter into contract as provided
                in
                the
                Indian Contract Act 1872.
            </li>

            <li>
                The DIRECT SELLER is a non-exclusive contractor. DIRECT SELLER is not an agent/ employee/ partner or
                legal
                representative of The Company for any purpose whatsoever. He / She shall be responsible for his own
                business
                and
                compliance of the central, state and local statues and Regulations and all applicable laws.
            </li>

            <li>
                The DIRECT SELLER shall abide by sales policy/ Rules/ Procedures/ Terms and Conditions of the company in
                vogue
                or as
                amended anytime in the Future.
            </li>

            <li>
                There is no any kind of fixed income. Commission/ Incentives, Royalty, Rewards etc all are based on the
                sale
                volume
                generated by the DIRECT SELLER himself / herself as well by his/her team and are calculated as per pay
                plan
                of
                the
                company. Company reserves the right to change Business Rewards Points/ Point Value Ratios/ other
                components
                of
                pay plan
                and method of Pay Plan at any point of time without prior notice.
            </li>

            <li>
                Without prior approval from the Company, DIRECT SELLER shall refrain from: a) Promoting company
                Products/Services/activities through any form of advertisement.
                b) Recruiting new DIRECT SELLER through any type of media.
            </li>

            <li>
                The company shall no way be responsible for any past, present or future liability Incurred by the DIRECT
                SELLER
                while
                conducting the business with the Company.
            </li>

            <li>
                The DIRECT SELLER shall purchase the company's Products/Services as per the DIRECT SELLER pricelist and
                shall
                sale
                the Products/Services to customers at MRP (Maximum Retail Price) printed on the product pack label.
            </li>

            <li>
                All taxes, duties government levies applicable to the sales made by the DIRECT SELLER shall be payable
                by
                the
                DIRECT
                SELLER as per the procedure and law of the land. There will be 5 % TDS deduction on all payments to
                DIRECT
                SELLER by
                company if DIRECT SELLER fails to provide PAN number there will be 20 % TDS deduction.
            </li>

            <li>
                Goods and Services Tax (GST) on the income of the DIRECT SELLER (if applicable) will be duly paid by the
                DIRECT
                SELLER to the Government as per the applicable norms.
            </li>

            <li>
                Any other taxes, levies on and above the income of the DIRECT SELLER earned from the company will be
                borne
                and
                duly
                paid by the DIRECT SELLER to the concern authorities as per applicable norms.
            </li>

            <li>
                The DIRECT SELLER shall promote the company's Products/Services in accordance with the contents of the
                company's
                printed document & support material supplied by the company and prohibited to make any amendments
                Thereto or
                revision
                thereof by the DIRECT SELLER.
            </li>

            <li>
                The DIRECT SELLER shall not sale the company's Products/Services to or through retail outlets/shops as
                it is
                contrary to the Sales Policy of the company.
            </li>

            <li>
                The DIRECT SELLER will seek prior permission of the Company before selling or supplying Products /
                Services
                to
                or
                through E–Commerce Companies and Online Marketplace
            </li>

            <li>
                The company is having the absolute rights to terminate the Distributorship, in the event of failure on
                part
                of
                the
                DIRECT SELLER, to comply with the terms and conditions and code of ethics with 15 days show cause
                notice.
            </li>

            <li>
                A terminated DIRECT SELLER can join fresh with a new application only after 6 months from the date of
                termination.
            </li>

            <li>
                The DIRECT SELLER can neither claim that the product is a cure for diseases nor he/she should do any
                diagnosis
                and
                suggest treatment unless he/she is a registered medical practitioner.
            </li>

            <li>
                Company has its consumer grievance redressal cell to resolve any complain related to companies products,
                services,
                payment etc. anyone who has such complain may contact grievance redressal cell in writing cell will
                insure
                to
                resolve
                the issue within 40 days of its receiving.
            </li>

            <li>
                Cooling off Period: New DIRECT SELLER can surrender his / her business within 30 days from the date of
                sign
                up
                under
                Cooling off Period. They can return unsold products to the company with original Invoice as per return
                policy of
                the
                Company, Such products are must be into resalable condition.
            </li>

            <li>
                The DIRECT SELLER will never make any false claims of high incentives, income and about business
                opportunities.
                He/she has to communicate the company's business plan without any changes.
            </li>

            <li>
                For all purposes, only English version of printed material from the company will be taken as an official
                copy.
            </li>

            <li>
                These Term and Conditions are, an integral part of the BIOALEXIS TRADING INDIA PRIVATE LIMITED and It is
                the
                responsibility of each DIRECT SELLER to read, understand and, adhere to, and ensure that he/she is aware
                of
                and
                operating under the most current version of these Policies and Procedures.
            </li>

            <li>
                The company is the Authority to interpret the rules, regulations, instructions and sales policy
                applicable
                to
                and
                governing the conduct of the DIRECT SELLER.
            </li>

            <li>
                Before visiting any prospect, for product selling or business presentation, DIRECT SELLER will always
                take
                prior
                appointment as well will carry his/her DIRECT SELLER identity card.
            </li>

            <li>
                lf there is no any business transaction continuously for 2 Years, the Distributorship will be terminated
                without
                prior notice.
            </li>

            <li>
                A DIRECT SELLER cannot become distributor with as well actively participate in any role into activity of
                any
                other
                direct selling company; violation of this will result into termination from being an DIRECT SELLER .
            </li>

            <li>
                A DIRECT SELLER must not make any negative or disparaging remarks about the company.
            </li>

            <li>
                The company reserve the right to change, modify and alter the business plan, rules, regulations, prices,
                terms,
                conditions and code of ethics without any prior notice or intimation to the DIRECT SELLER .
            </li>

            <li>
                The applicant should read, understand all the Rules, Policies, Terms, Conditions and code of ethics
                printed
                in
                the
                company's business manual and seek all clarification and explanations from his sponsor before signing
                the
                application
                form.
            </li>

            <li>
                Applicant Shall Fill the registration from online provided on companies website www.bioalexis.com take
                it's
                printout
                and sign and deliver it along with the supporting documents as requested in the Format, for Registration
                you
                may
                scan it
                and mail to our email support@bioalexis.com .
            </li>

            <li>
                One who wants to purchase the Company products/services as well become distributor, applicant shall
                deposit
                the
                amount in the company's bank account only and intimate to Company on its Customer Care No. 1234567890 or
                email
                to
                support@bioalexis.com .
            </li>

            <li>
                Company has not authorized any DIRECT SELLER to collect cash from any individual for product purchase
                from
                us
                and
                the payment shall be deposited in the company bank account directly. COMPANY will not be responsible for
                any
                cash
                payment made to any individual.
            </li>

            <li>
                Any dispute, differences or claims arising out of as in connection with this agreement shall be
                submitted to
                Arbitration and shall be referred to the sole Arbitrator under the Arbitration Act and Rules. The venue
                of
                such
                arbitration shall be at Raipur and the award of the Arbitrator shall be final and binding on all
                parties.
                The
                courts at
                Raipur shall alone have jurisdiction in relation to this Arbitration Agreement and any award arising
                there
                from.
            </li>

            <li>
                BIOALEXIS TRADING INDIA PRIVATE LIMITED is a Private Limited Company incorporated under the companies
                Act of
                1956,
                registered with the registrar of companies, having its head office at Raipur Chhattisgarh. All disputes
                or
                differences
                shall be adjudicated upon by a court of appropriate jurisdiction at Raipur only.
            </li>


    </div>
    <?php require_once 'partials/scripts.php' ?>
    <?php require_once 'partials/footer.php' ?>
</body>

</html>